logo: SCIE4701_icon.png
theme: jekyll-theme-cayman
title: SCIE 4701/02  Science &amp; Technology Innovation, Commercialization, &amp; Entrepreneurship
description: Official site for the course offered by the Faculty of Science, Dalhousie University.
# Google Analytics
google_analytics: 
